# Generated by Django 3.2.16 on 2023-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersId',
            fields=[
                ('LoginName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'UsersId',
                'managed': False,
            },
        ),
    ]
